config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "books#all_books_index"

  resources :users, only: [] do
    resources :books, only: [:index, :new, :create]
    post "goodreads_create", to: "books#goodreads_create"
  end

  resources :books, only: [:edit, :update, :destroy] do
    resources :chapters, only: [:index, :create]
  end

  resources :chapters, only: [:show, :edit, :update, :destroy]

  get "goodreads_search", to: "books#goodreads_search"

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :books, through: :book_authors
  has_many :book_authors

  validates :name, presence: true
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user
  has_many :chapters
  has_many :authors, through: :book_authors, autosave: true
  has_many :book_authors, autosave: true, dependent: :destroy
  accepts_nested_attributes_for :book_authors
  accepts_nested_attributes_for :authors

  validates :title, presence: true
  validates :user, presence: true
end

app/models/book_author.rb
class BookAuthor < ActiveRecord::Base
  belongs_to :book
  belongs_to :author
  accepts_nested_attributes_for :author
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  belongs_to :book

  validates :title, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence: true, uniqueness: true
  validates_presence_of :password_confirmation, message: "can't be blank"

  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
    devise_parameter_sanitizer.for(:account_update) <<
      [:username, :name, :occupation]
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:all_books_index]

  def all_books_index
    if params[:search]
      if params[:search_type] == "title"
        @all_books = Book.where("title ILIKE ?", "%#{params[:search]}%")
      elsif params[:search_type] == "isbn"
        @all_books = Book.where("isbn_10 LIKE ? OR isbn_13 LIKE ?",
          params[:search], params[:search])
      elsif params[:search_type] == "author"
        @all_books = []
        authors = Author.where("name ILIKE ?", "%#{params[:search]}%")
        authors.each do |author|
          author.books.each { |book| @all_books << book }
        end
      end
    else
      @all_books = Book.order("created_at DESC")
    end
  end

  def index
    @user = current_user
    @books = @user.books
  end

  def new
    @user = current_user
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @user = current_user
    @book.user = @user
    add_authors_from_author_attributes(@book, params[:book][:authors_attributes])

    if @book.save
      flash[:notice] = "Book added!"
      redirect_to book_chapters_path(@book)
    else
      flash.now[:notice] = "Book could not be saved. See problems below."
      render :new
    end
  end

### GOODREADS METHODS

  def goodreads_search
    goodreads_client = Goodreads::Client.new
    search = goodreads_client.search_books(params[:search])
    @results_to_display_on_view = parse_goodreads_search(search)
  end

  def goodreads_create
    goodreads_client = Goodreads::Client.new
    goodreads_book = goodreads_client.book(params[:goodreads_book_id])

    book = create_book_with_book_info(goodreads_book)

    if book.save
      redirect_to book_chapters_path(book.id)
    else
      flash[:notice] = "Sorry! There was an error."
      render 'goodreads_search'
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :publication_year)
  end

  #these methods are used when user adds book manually
  def add_authors_from_author_attributes(book, author_attr_hash)
    author_attr_hash.each do |number, author|
      add_author(book, author)
    end
  end

  def add_author(book, author_info)
    book.authors << Author.find_or_initialize_by(name: author_info['name'])
  end

  #these methods are for when the goodreads search by id is used
  def create_book_with_book_info(goodreads_book)
    book_info_hash = get_book_info_hash(goodreads_book)
    book = Book.new(book_info_hash)
    book.user = current_user
    book.authors = create_authors_from_goodreads_book(goodreads_book)
    book
  end

  def get_book_info_hash(goodreads_book)
    {
      title: goodreads_book.title,
      goodreads_book_id: goodreads_book.id,
      isbn_10: goodreads_book.isbn,
      isbn_13: goodreads_book.isbn13
    }
  end

  def create_authors_from_goodreads_book(goodreads_book)
    authors = []
    goodreads_book.authors.values.each do |author|
      author_to_add = Author.find_or_initialize_by(goodreads_author_id: author.id)
      author_to_add.name = author.name
      authors << author_to_add
    end
    authors
  end


  #these methods are for when the goodreads search by title, author, or isbn function is used
  def parse_goodreads_search(search)
    books = []
    search.results.work.each do |book|
      books << get_book_info_from_search(book)
    end
    books
  end

  def get_book_info_from_search(book)
    {
      title: book.best_book.title,
      goodreads_book_id: book.best_book.id,
      author: book.best_book.author.name,
      goodreads_author_id: book.best_book.author.id,
      img_url: book.best_book.image_url,
      original_publication_year: book.original_publication_year
    }
  end


end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :authenticate_user!

  def index
    @book = Book.find(params[:book_id])
    @chapters = @book.chapters
    @chapter = Chapter.new
  end

  def show
    @chapter = Chapter.find(params[:id])
  end

  def create
    @chapter = Chapter.new(chapter_params)
    @book = Book.find(params[:book_id])
    @chapter.book_id = params[:book_id]

    if @chapter.save
      flash[:notice] = "Your chapter has been added."
      redirect_to book_chapters_path(@chapter.book_id)
    else
      flash.now[:notice] = "You're chapter could not be added. See errors below."
      @book = Book.find(params[:book_id])
      @chapters = @book.chapters
      render 'chapters/index'
    end
  end

  private

  def chapter_params
    params.require(:chapter).permit(:title, :summary, :tldr, :reflection, :key_concepts)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/views/books/all_books_index.html.erb
<h1>Public Books</h1>

<ol>
  <% @all_books.each do |book| %>
    <li>
      <%= book.title %>
    </li>
  <% end %>
</ol>

app/views/books/goodreads_search.html.erb
<h3>Did you mean one of these books?</h3>

<ol>
  <% @results_to_display_on_view.each do |book| %>
    <li>
      <%= book[:title] %> by <%= book[:author] %>
      <%= button_to("This one!", user_goodreads_create_path(current_user),
      params: { goodreads_book_id: book[:goodreads_book_id] },
      method: "post", class: 'goodreads-selection-btn')%>
    </li>
  <% end %>
</ol>

app/views/books/index.html.erb
<h1>Your Books</h1>

<ol>
  <% @books.each do |book| %>
    <li>
      <%= book.title %>
    </li>
  <% end %>
</ol>

<%= link_to 'Add a Book', new_user_book_path(current_user) %>

app/views/books/new.html.erb
<h3>Add a Book</h3>

<h4>Search for a book with the title, author, or ISBN (recommended).</h4>
<p>Powered by Goodreads</p>
<%= form_tag({controller: "books", action: 'goodreads_search'}, method: "get", id: 'goodreads-search-form') do %>
  <%= text_field_tag :search, params[:search], placeholder: 'Find your book' %>
  <%= submit_tag 'Search', name: nil %>
<% end %>


<p>Or add a book manually</p>

<%= simple_form_for [@user, @book] do |f| %>
  <div class="form-inputs">
    <%= f.input :title, required: true, autofocus: true %>
    <%= f.simple_fields_for :authors, @book.authors.build do |authors| %>
      <%= authors.input :name, label: "Author", required: false %>
    <% end %>
    <%= f.input :publication_year, required: false, label: "Original Publication Year" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Add Book" %>
  </div>
<% end %>

app/views/chapters/index.html.erb
<h3>Your Notes for "<%= @book.title %>"</h3>
Book Details:</br>
Authors: <% @book.authors.each do |author| %>
  <%= author.name %>
<% end %>
<ul>
  <% @chapters.each do |chapter| %>
    <li><%= chapter.title %></li>
  <% end %>
</ul>

<h5>Add a Chapter for <%= @book.title %></h5>

<%= simple_form_for [@book, @chapter] do |f| %>
  <div class="form-inputs">
    <%= f.input :title, required: true, autofocus: true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Add Chapter" %>
  </div>
<% end %>

app/views/chapters/show.html.erb
<%= @chapter.title %>
<%= @chapter.summary %>
<%= @chapter.tldr %>
<%= @chapter.reflection %>
<%= @chapter.key_concepts %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Art of Reading" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <%= notice if notice %>
  <%= alert if alert %>

  <nav class="top-bar">
    <ul class="title-area">
      <li class="name"><h1><%= link_to 'Art of Reading', root_path %></h1></li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <% if user_signed_in? %>
          <li class="has-dropdown">
            <a data-dropdown="hover1" data-options="is_hover:true"><%= current_user.email %></a>
            <ul id="hover1" class="f-dropdown" data-dropdown-content>
              <li><%= link_to 'Your Books', user_books_path(current_user) %></li></br>
              <li><%= link_to 'Add a Book', new_user_book_path(current_user) %></li></br>
              <li><%= link_to 'Edit profile', edit_user_registration_path %></li></br>
              <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li></br>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Sign up', new_user_registration_path%></li>
          <li><%= link_to 'Login', new_user_session_path%></li>
        <% end %>
      </ul>
    </section>
  </nav>

    <div id="search">
      <%= form_tag(root_path, method: "get", id: 'search-form') do %>
        <%= text_field_tag :search, params[:search], placeholder: 'Search Summaries' %>
        <%= radio_button_tag(:search_type, "title", checked = true) %>
        <%= label_tag(:search_type_title, "Title") %>
        <%= radio_button_tag(:search_type, "author") %>
        <%= label_tag(:search_type_author, "Author") %>
        <%= radio_button_tag(:search_type, 'isbn') %>
        <%= label_tag(:search_type_isbn, "ISBN") %>
        <%= submit_tag "Search", name: nil %></li>
      <% end %>
    </div>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>